import type { NextPage } from 'next'
import Head from 'next/head'
import { SectionOneHome } from '../components/Home/SectionOneHome'
import { SectionTwoHome } from '../components/Home/SectionTwoHome'
import { SectionThreeHome } from '../components/Home/SectionThreeHome'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Agência Ousar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Anton&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
      </Head>
      <div className="bg-black min-h-screen bg-[url('/images/bg-section-one.png')] bg-cover bg-center flex">
        <SectionOneHome />
      </div>
      <div className="bg-black min-h-screen py-8 flex justify-center items-center">
        <SectionTwoHome />
      </div>
      <div className="bg-black min-h-screen py-8 flex justify-center items-center">
        <SectionThreeHome />
      </div>
    </>
  )
}

export default Home

